### ISSUE TITLE
Damage events

### ISSUE THREAD

**Issue by mcmonkey4eva** [FreneticCSharp/UnturnedFrenetic#10]
Events for things being damaged but not necessarily dying!

**Comment by Morphan1** [comment]
I'm just gonna put this here
- [x] player damage
- [x] zombie damage
- [x] animal damage
- [x] resource damage
- [x] barricade damage
- [x] structure damage
- [x] vehicle damage
- [x] all-encompassing "entity damaged" event

**Comment by Morphan1** [comment]
All done! Now we just need those blasted post events
