### ISSUE TITLE
Entity position/velocity/etc. commands

### ISSUE THREAD

**Issue by mcmonkey4eva** [FreneticCSharp/UnturnedFrenetic#17]
Need a quick way to set the common properties of an entity!
- [x] Teleport (Position)
- [x] Shoot/setvel/whatever (Velocity)

**Comment by mcmonkey4eva** [comment]
position/vel, what else is in this category?

**Comment by Morphan1** [comment]
Well... Launch was added. Do you want to add something with a parabola? Or...
