### ISSUE TITLE
Control/read power details

### ISSUE THREAD

**Issue by mcmonkey4eva** [FreneticCSharp/UnturnedFrenetic#19]
As in power from a generator

**Comment by Morphan1** [comment]
I think this is as done as it can be atm fc366ba

**Comment by mcmonkey4eva** [comment]
`READ` power details is not done, is it?

**Comment by Morphan1** [comment]
@mcmonkey4eva weird, for some reason I saw #11 as the one with that in it. these are both the same issue though

**Comment by mcmonkey4eva** [comment]
Yeah uh... I thought these would be separate things. Like this issue was specifically for like.. powering things without a power source and so on, but that's not possible so~

**Comment by mcmonkey4eva** [comment]
Other issue still needs reading stuff for it tho
