### ISSUE TITLE
Take Command

### ISSUE THREAD

**Issue by mcmonkey4eva** [FreneticCSharp/UnturnedFrenetic#4]
We have an inventory give command, we need a take command to match it!

**Comment by mcmonkey4eva** [comment]
Also this and give should support non-player inventories tooooooooooooooooooooooooooo

**Comment by mcmonkey4eva** [comment]
Oh, we got one forever ago

**Comment by Morphan1** [comment]
They don't support non-player inventories yet though... future problems, I think
